# Generated by Django 5.2.1 on 2025-05-18 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('C', 'Canceled')], default='P', max_length=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('admin_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='api.matchrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('children', models.IntegerField(default=0)),
                ('education', models.CharField(choices=[('HS', 'High School'), ('BA', "Bachelor's Degree"), ('MA', "Master's Degree"), ('PHD', 'PhD'), ('OTH', 'Other')], max_length=3)),
                ('occupation', models.CharField(max_length=100)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('religiosity', models.CharField(choices=[('VR', 'Very Religious'), ('R', 'Religious'), ('MR', 'Moderately Religious'), ('NVR', 'Not Very Religious')], max_length=3)),
                ('bio', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='api.profile')),
            ],
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='api.profile'),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='api.profile'),
        ),
        migrations.CreateModel(
            name='MatchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46+', '46+')], max_length=10)),
                ('height_range', models.CharField(choices=[('150-160', '150-160 cm'), ('161-170', '161-170 cm'), ('171-180', '171-180 cm'), ('181+', '181+ cm')], max_length=10)),
                ('education_preference', models.CharField(blank=True, choices=[('HS', 'High School'), ('BA', "Bachelor's Degree"), ('MA', "Master's Degree"), ('PHD', 'PhD'), ('OTH', 'Other')], max_length=3, null=True)),
                ('marital_status_preference', models.CharField(blank=True, choices=[('S', 'Single'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1, null=True)),
                ('has_children_preference', models.BooleanField(blank=True, null=True)),
                ('country_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('religiosity_preference', models.CharField(blank=True, choices=[('VR', 'Very Religious'), ('R', 'Religious'), ('MR', 'Moderately Religious'), ('NVR', 'Not Very Religious')], max_length=3, null=True)),
                ('additional_preferences', models.TextField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='api.profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='matchrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
